-- Auto-generated from roadmap markdown. Do not edit by hand — regenerate via scripts/generate_seed_sql.py
begin;

insert into public.roadmap_metadata (id, title, total_phases, total_topics, total_realistic_hours, source_stated_hours, months_at_40hrs_week, dsa_easy_target, dsa_medium_target)
values (1, 'Zero to Elite — The Complete Engineering Roadmap', 21, 375, 3034, 2700, 17.5, 75, 50)
on conflict (id) do update set title=excluded.title, total_phases=excluded.total_phases, total_topics=excluded.total_topics, total_realistic_hours=excluded.total_realistic_hours, source_stated_hours=excluded.source_stated_hours, months_at_40hrs_week=excluded.months_at_40hrs_week, dsa_easy_target=excluded.dsa_easy_target, dsa_medium_target=excluded.dsa_medium_target, updated_at=now();

delete from public.phases;
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-01', '01', 'Developer Environment & Foundations', 'Foundation', 185, NULL, '"Setting up my dev environment the right way" — your terminal/editor config, ESLint+Prettier rules, and why you picked them.**', false, 0);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-01b', '01b', 'TypeScript Mastery', 'Foundation', 80, NULL, 'One TypeScript gotcha you hit and fixed — a real type error, not a tutorial recap.**', false, 1);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-02', '02', 'React + Next.js Core', 'Foundation', 213, NULL, 'A short screen-recording or GIF of your first deployed Next.js page going live on Vercel.**', false, 2);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-03', '03', 'UI System & Styling', 'Foundation', 135, NULL, 'Before/after screenshots of your UI system — component library, dark mode, design tokens.**', false, 3);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-04', '04', 'State, Data Fetching & Advanced React', 'Core', 153, NULL, '"Why I chose TanStack Query + Zustand over Redux" — a real architectural decision with trade-offs.**', false, 4);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-05', '05', 'Backend + Database + Auth', 'Core', 314, NULL, 'Your auth flow diagram (JWT + httpOnly cookies) — one of the most commonly asked-about topics by other learners.**', false, 5);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-06', '06', 'Testing + CI/CD + Deployment', 'Core', 155, 'A', 'Your green CI badge, first time all tests + Docker build pass in GitHub Actions.**', false, 6);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-06b', '06b', 'React Native (Mobile)', 'Core', 111, 'A2', NULL, false, 7);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-07', '07', 'API Documentation & Developer Tooling', 'Core', 71, 'B', 'Your OpenAPI/Swagger docs page — link it, don''t just say you have API docs.**', false, 8);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-08', '08', 'DSA & Interview Preparation', 'Core', 331, '★1', 'Skip public posting this phase — DSA grind isn''t a visibility play. Log progress privately (see notes doc).**', true, 9);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-09', '09', 'Caching + Email + Payments', 'Advanced', 98, NULL, '"I integrated Razorpay and here''s what nobody tells you about test mode" — a real, specific gotcha post.**', false, 10);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-10', '10', 'Monitoring & Analytics', 'Advanced', 103, 'C', 'A screenshot of your PostHog/Sentry dashboard showing real usage or error data from ClientSync.**', false, 11);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-11', '11', 'Real-Time + Search + PostgreSQL Internals', 'Advanced', 164, '★2', 'A short demo of real-time features (WebSockets/SSE) working in ClientSync.**', false, 12);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-12', '12', 'AI/RAG + Production AI Patterns', 'Advanced', 207, 'D', 'Your RAG pipeline or AI feature — show the actual output, not just "I added AI."**', false, 13);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-13', '13', 'Advanced Browser APIs + Collaboration', 'Advanced', 137, NULL, 'A demo of real-time collaboration (Yjs) — two cursors editing the same doc live.**', false, 14);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-14', '14', 'Load Testing + Security Deep Dive', 'Advanced', 89, NULL, '"I ran a load test on my own app and here''s what broke" — an honest post about a real weakness you found and fixed.**', false, 15);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-15', '15', 'Build Tooling + CSS-in-JS', 'Advanced', 44, NULL, 'Skip public posting — build tooling changes aren''t visible or interesting to an outside audience.**', true, 16);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-16', '16', 'Infrastructure', 'Expert', 175, NULL, 'Your infrastructure diagram — Terraform + Kubernetes setup, even a simple one.**', false, 17);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-17', '17', 'Architectural Patterns', 'Expert', 178, '3', '"Why I used the Saga pattern instead of a distributed transaction" — one architectural pattern, explained simply.**', false, 18);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-18', '18', 'Engineering Craft + Package Publishing', 'Expert', 62, NULL, 'Your first published npm package, however small.**', false, 19);
insert into public.phases (id, phase_number, title, band, estimated_hours, exit_point_code, build_in_public_prompt, skip_build_in_public, order_index) values ('phase-19', '19', 'Career & Community', 'Expert', 29, 'E', 'Your full journey — a retrospective post: what you built, what surprised you, what you''d do differently.**', false, 20);

insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-001', 'phase-01', 7, 'VS Code', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-002', 'phase-01', 9, 'Bash', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-003', 'phase-01', 8, 'nvm + npm', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-004', 'phase-01', 10, 'SSH Keys', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-005', 'phase-01', 5, 'Git + GitHub (Foundations Only — local + remote basics)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-006', 'phase-01', 1, 'HTML5', 10);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-007', 'phase-01', 2, 'CSS3', 15);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-008', 'phase-01', 8, 'JavaScript — Language Core', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-009', 'phase-01', 9, 'Core Data Structures', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-010', 'phase-01', 10, 'Error Handling', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-011', 'phase-01', 11, 'Regular Expressions', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-012', 'phase-01', 12, 'Prototypes & Inheritance', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-013', 'phase-01', 13, 'Classes', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-014', 'phase-01', 14, 'Iterators & Generators', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-015', 'phase-01', 15, 'Symbols', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-016', 'phase-01', 16, 'Collections', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-017', 'phase-01', 17, 'Property Descriptors & Object Internals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-018', 'phase-01', 18, 'Reflect API', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-019', 'phase-01', 19, 'Proxy', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-020', 'phase-01', 20, 'Meta Programming', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-021', 'phase-01', 21, 'Modules', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-022', 'phase-01', 22, 'Event Loop', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-023', 'phase-01', 23, 'Asynchronous JavaScript', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-024', 'phase-01', 24, 'Advanced Promises', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-025', 'phase-01', 25, 'Advanced Async', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-026', 'phase-01', 26, 'HTTP & APIs', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-027', 'phase-01', 27, 'DOM', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-028', 'phase-01', 28, 'Events', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-029', 'phase-01', 29, 'Forms (JS side)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-030', 'phase-01', 30, 'Browser Storage', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-031', 'phase-01', 31, 'Timing Functions', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-032', 'phase-01', 32, 'Browser APIs', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-033', 'phase-01', 33, 'Advanced Browser APIs (Observers & Performance)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-034', 'phase-01', 34, 'Networking (Realtime)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-035', 'phase-01', 35, 'Binary Data', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-036', 'phase-01', 36, 'Workers', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-037', 'phase-01', 37, 'Internationalization', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-038', 'phase-01', 38, 'Security', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-039', 'phase-01', 39, 'Browser Rendering & Performance', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-040', 'phase-01', 40, 'Frontend Performance Techniques', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-041', 'phase-01', 41, 'Memory Leaks', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-042', 'phase-01', 42, 'Functional Programming', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-043', 'phase-01', 43, 'Advanced Functional Programming', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-044', 'phase-01', 44, 'Design Patterns', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-045', 'phase-01', 45, 'JavaScript Architecture', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-046', 'phase-01', 46, 'Algorithms & Problem Solving in JavaScript', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-047', 'phase-01', 47, 'Advanced Algorithms', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-048', 'phase-01', 48, 'Testing', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-049', 'phase-01', 49, 'Debugging', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-050', 'phase-01', 50, 'Package Ecosystem & Tooling', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-051', 'phase-01', 51, 'JavaScript Best Practices', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-052', 'phase-01', 52, 'JavaScript Engine Internals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-053', 'phase-01', 53, 'JavaScript Specifications', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-054', 'phase-01', 54, 'Modern JavaScript Features (ES6+) — Consolidation Checkpoint', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-055', 'phase-01', 55, 'TypeScript — Introduction', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-056', 'phase-01', 56, 'tsconfig.json (Deep Dive)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-057', 'phase-01', 57, 'Type Narrowing (Deep Dive)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-058', 'phase-01', 58, 'Discriminated Unions', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-059', 'phase-01', 59, 'Generics', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-060', 'phase-01', 60, 'as const & satisfies', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-061', 'phase-01', 61, 'Utility Types', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-062', 'phase-01', 62, 'Mapped Types', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-063', 'phase-01', 63, 'Conditional Types', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-064', 'phase-01', 64, 'Template Literal Types', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-065', 'phase-01', 65, 'Declaration Files', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-066', 'phase-01', 66, 'Zod', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-067', 'phase-01', 11, 'SQL Fundamentals', 23);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-068', 'phase-01', 68, 'Git + GitHub (Collaboration Deep Dive)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-069', 'phase-01', 6, 'Conventional Commits', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-070', 'phase-01', 12, 'ESLint', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01-071', 'phase-01', 13, 'Prettier', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl01', 'phase-01b', 1, 'generics', 11);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl02', 'phase-01b', 2, 'discriminated unions', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl03', 'phase-01b', 3, 'conditional types', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl04', 'phase-01b', 4, 'mapped types', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl05', 'phase-01b', 5, 'utility types', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl06', 'phase-01b', 6, 'template literal types', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl07', 'phase-01b', 7, 'satisfies operator', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl08', 'phase-01b', 8, 'as const', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl09', 'phase-01b', 9, 'type narrowing', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl10', 'phase-01b', 10, 'tsconfig.json', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl11', 'phase-01b', 11, 'declaration files (.d.ts)', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-01b-tbl12', 'phase-01b', 12, 'zod', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-001', 'phase-02', 1, 'React Fundamentals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-002', 'phase-02', 2, 'Component Lifecycle & Effects', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-003', 'phase-02', 3, 'The Full Hook Set', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-004', 'phase-02', 4, 'Forms & Events', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-005', 'phase-02', 5, 'Component Design Patterns', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-006', 'phase-02', 6, 'Error Boundaries & Portals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-007', 'phase-02', 7, 'Suspense & Concurrent Rendering (Client-Side)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-008', 'phase-02', 8, 'Routing Fundamentals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-009', 'phase-02', 9, 'Server Components vs Client Components', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-010', 'phase-02', 10, 'Data Fetching & the Caching Model', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-011', 'phase-02', 11, 'Server Actions & Mutations', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-012', 'phase-02', 12, 'Route Handlers (API Routes)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-013', 'phase-02', 13, 'Static Generation & ISR', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-014', 'phase-02', 14, 'Metadata, SEO & Optimization APIs', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-015', 'phase-02', 15, 'Middleware', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-016', 'phase-02', 16, 'Fetch API (Next.js-Extended Semantics)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-017', 'phase-02', 3, 'Route Groups', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-018', 'phase-02', 6, 'notFound()', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-019', 'phase-02', 4, 'Parallel Routes', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-020', 'phase-02', 5, 'Intercepting Routes', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-021', 'phase-02', 7, 'revalidatePath()', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-022', 'phase-02', 8, 'revalidateTag()', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-023', 'phase-02', 23, 'Browser Storage', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-024', 'phase-02', 24, 'React Router v6 (Non-Next.js Context)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-025', 'phase-02', 25, 'Client-Side Data Fetching Libraries (Conceptual Prerequisite)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-026', 'phase-02', 9, 'HydrationBoundary and dehydrate()', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-027', 'phase-02', 11, 'Vercel', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-028', 'phase-02', 12, 'Vercel Edge Functions', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-029', 'phase-02', 13, 'Vercel Edge Runtime', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-030', 'phase-02', 30, 'Image Optimization Utilities: plaiceholder', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-02-031', 'phase-02', 31, 'GitHub Pages (Alternative Static Deployment)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-001', 'phase-03', 3, 'CSS Custom Properties', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-002', 'phase-03', 2, 'CSS @layer (Cascade Layers)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-003', 'phase-03', 2, 'CSS Modules', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-004', 'phase-03', 16, 'BEM (Block Element Modifier)', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-005', 'phase-03', 1, 'Tailwind CSS', 22);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-006', 'phase-03', 5, 'clsx', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-007', 'phase-03', 6, 'tailwind-merge', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-008', 'phase-03', 7, 'CVA (Class Variance Authority)', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-009', 'phase-03', 8, 'Radix UI', 8);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-010', 'phase-03', 9, 'shadcn/ui', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-011', 'phase-03', 10, 'next-themes', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-012', 'phase-03', 11, 'react-hook-form', 14);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-013', 'phase-03', 13, 'Zod (react-hook-form Integration)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-014', 'phase-03', 13, 'date-fns', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-015', 'phase-03', 14, 'lodash-es', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-016', 'phase-03', 15, 'nanoid', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-017', 'phase-03', 17, 'Style Dictionary', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-03-018', 'phase-03', 18, 'vanilla-extract', 8);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-001', 'phase-04', 1, 'React Context — Revisited: Where It Breaks Down', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-002', 'phase-04', 2, 'Zustand', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-003', 'phase-04', 3, 'TanStack Query v5', 23);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-004', 'phase-04', 4, 'tRPC v11', 24);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-005', 'phase-04', 5, 'XState v5', 20);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-006', 'phase-04', 6, 'Stately Studio', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-007', 'phase-04', 7, 'React.lazy — Applied', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-008', 'phase-04', 8, 'Suspense — For Data', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-009', 'phase-04', 9, 'react-error-boundary', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-010', 'phase-04', 10, 'ReactDOM.createPortal — Applied', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-011', 'phase-04', 11, 'Intersection Observer', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-012', 'phase-04', 12, 'ResizeObserver', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-013', 'phase-04', 14, 'TanStack Virtual', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-04-014', 'phase-04', 13, 'React DevTools Profiler', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-001', 'phase-05', 1, 'Node.js', 34);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-002', 'phase-05', 2, 'Express.js', 25);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-003', 'phase-05', 3, 'REST APIs', 17);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-004', 'phase-05', 4, 'express-async-errors', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-005', 'phase-05', 5, 'CORS', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-006', 'phase-05', 6, 'Helmet.js', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-007', 'phase-05', 7, 'express-rate-limit', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-008', 'phase-05', 8, 'DOMPurify (Server-Side Sanitization)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-009', 'phase-05', 9, 'compression', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-010', 'phase-05', 10, 'Supertest', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-011', 'phase-05', 11, 'PostgreSQL', 52);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-012', 'phase-05', 12, 'Prisma', 25);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-013', 'phase-05', 13, 'Supabase', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-014', 'phase-05', 14, 'Neon', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-015', 'phase-05', 15, 'EXPLAIN ANALYZE', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-016', 'phase-05', 16, 'bcrypt', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-017', 'phase-05', 21, 'HMAC-SHA256', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-018', 'phase-05', 17, 'JWT (JSON Web Tokens)', 15);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-019', 'phase-05', 18, 'jose', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-020', 'phase-05', 19, 'httpOnly Cookies', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-05-021', 'phase-05', 20, 'SameSite=Lax', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-001', 'phase-06', 1, 'Vitest', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-002', 'phase-06', 2, 'React Testing Library', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-003', 'phase-06', 3, '@testing-library/user-event', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-004', 'phase-06', 4, 'MSW (Mock Service Worker)', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-005', 'phase-06', 5, 'v8 Coverage', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-006', 'phase-06', 6, 'Codecov', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-007', 'phase-06', 7, 'Playwright', 18);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-008', 'phase-06', 8, 'GitHub Actions', 16);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-009', 'phase-06', 9, 'Docker', 25);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-010', 'phase-06', 10, 'Docker Compose', 10);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-011', 'phase-06', 11, 'GitHub Container Registry (GHCR)', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-012', 'phase-06', 12, 'docker/build-push-action', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-013', 'phase-06', 13, 'Render', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-014', 'phase-06', 15, 'HTTP/2', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06-015', 'phase-06', 14, 'shields.io', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-001', 'phase-06b', 1, 'React Native Fundamentals', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-002', 'phase-06b', 2, 'Expo + EAS Build', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-003', 'phase-06b', 3, 'React Navigation', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-004', 'phase-06b', 4, 'Flexbox Layout Differences (RN vs Web)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-005', 'phase-06b', 5, 'AsyncStorage + Offline-First Sync', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-006', 'phase-06b', 6, 'expo-secure-store', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-007', 'phase-06b', 7, 'Native APIs (Camera, Push, Permissions)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-008', 'phase-06b', 8, 'Platform-Specific Code (iOS vs Android)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-009', 'phase-06b', 9, 'FlatList Performance + Virtualization', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-010', 'phase-06b', 10, 'Hermes Engine', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-011', 'phase-06b', 11, 'New Architecture (Fabric + TurboModules)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-012', 'phase-06b', 12, 'App Store + Play Store Submission', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-06b-013', 'phase-06b', 13, 'EAS Update (OTA Updates)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-001', 'phase-07', 5, 'curl', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-002', 'phase-07', 3, 'Postman', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-003', 'phase-07', 4, 'Insomnia', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-004', 'phase-07', 1, 'OpenAPI 3.0', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-005', 'phase-07', 2, 'Swagger UI', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-006', 'phase-07', 6, 'Mermaid', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-07-007', 'phase-07', 7, 'GraphQL', 26);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-001', 'phase-08', 1, 'Two Pointers', 18);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-002', 'phase-08', 2, 'Sliding Window', 18);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-003', 'phase-08', 3, 'Binary Search', 18);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-004', 'phase-08', 11, 'Kadane''s Algorithm', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-005', 'phase-08', 6, 'HashMap / Frequency Count Patterns', 15);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-006', 'phase-08', 7, 'Stack Patterns', 15);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-007', 'phase-08', 8, 'Monotonic Stack', 15);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-008', 'phase-08', 9, 'Queue / Deque Patterns', 11);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-009', 'phase-08', 4, 'BFS / DFS', 30);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-010', 'phase-08', 10, 'Tree Traversal', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-011', 'phase-08', 10, 'Floyd''s Cycle Detection', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-012', 'phase-08', 13, 'Heap / Priority Queue', 22);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-013', 'phase-08', 5, 'Dynamic Programming (Memoization + Tabulation)', 58);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-014', 'phase-08', 14, 'Interview Frameworks (STAR, REACTO)', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-08-015', 'phase-08', 15, 'System Design Interview Basics', 19);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-001', 'phase-09', 1, 'Redis', 19);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-002', 'phase-09', 2, 'ioredis', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-003', 'phase-09', 3, 'PgBouncer', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-004', 'phase-09', 4, 'Upstash', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-005', 'phase-09', 5, '@upstash/ratelimit', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-006', 'phase-09', 6, 'Resend', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-007', 'phase-09', 7, 'React Email', 8);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-09-008', 'phase-09', 8, 'Razorpay', 19);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-001', 'phase-10', 1, 'AsyncLocalStorage', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-002', 'phase-10', 2, 'pino', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-003', 'phase-10', 3, 'winston', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-004', 'phase-10', 4, 'Sentry', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-005', 'phase-10', 5, 'UptimeRobot', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-006', 'phase-10', 6, 'Better Stack (formerly Logtail)', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-007', 'phase-10', 7, 'Axiom', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-008', 'phase-10', 8, 'Grafana Cloud', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-009', 'phase-10', 9, 'Loki', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-010', 'phase-10', 10, 'Datadog', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-011', 'phase-10', 11, 'CloudWatch', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-012', 'phase-10', 12, 'PostHog', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-013', 'phase-10', 13, 'posthog-js', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-014', 'phase-10', 14, 'posthog-node', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-015', 'phase-10', 15, 'Feature Flags', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-016', 'phase-10', 16, 'A/B Testing', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-017', 'phase-10', 17, 'Funnel Analysis', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-018', 'phase-10', 18, 'Session Recording', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-10-019', 'phase-10', 19, 'GDPR Consent Mode', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-001', 'phase-11', 1, 'SSE (EventSource)', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-002', 'phase-11', 2, 'WebSockets', 20);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-003', 'phase-11', 3, 'WebRTC', 18);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-004', 'phase-11', 4, 'B-Tree Indexes', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-005', 'phase-11', 5, 'Composite Indexes', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-006', 'phase-11', 6, 'Partial Indexes', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-007', 'phase-11', 7, 'Materialized Views', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-008', 'phase-11', 9, 'MVCC (Multi-Version Concurrency Control)', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-009', 'phase-11', 8, 'VACUUM', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-010', 'phase-11', 10, 'WAL (Write-Ahead Log)', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-011', 'phase-11', 11, 'Read Replicas', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-012', 'phase-11', 12, 'pg_stat_activity', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-013', 'phase-11', 13, 'PostgreSQL Full Text Search', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-014', 'phase-11', 14, 'Meilisearch', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-015', 'phase-11', 15, 'Typesense', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-11-016', 'phase-11', 16, 'Elasticsearch', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-001', 'phase-12', 1, 'OpenAI API', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-002', 'phase-12', 2, 'GPT-4o', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-003', 'phase-12', 11, 'Anthropic API', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-004', 'phase-12', 3, 'text-embedding-3-small', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-005', 'phase-12', 5, 'pgvector', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-006', 'phase-12', 6, 'IVFFlat Index', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-007', 'phase-12', 7, 'HNSW Index', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-008', 'phase-12', 8, 'RAG Pattern', 24);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-009', 'phase-12', 4, 'Vercel AI SDK', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-010', 'phase-12', 9, 'BullMQ', 16);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-011', 'phase-12', 10, 'Bull Board', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-012', 'phase-12', 12, 'Claude Model Tier Strategy', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-013', 'phase-12', 13, 'Extended Thinking', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-014', 'phase-12', 14, 'Prompt Caching', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-015', 'phase-12', 15, 'Tool Calling for Structured Extraction', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-016', 'phase-12', 16, 'Multi-Model Routing', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-017', 'phase-12', 17, 'AI Cost Tracking', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-018', 'phase-12', 18, 'Token Budget Enforcement', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-019', 'phase-12', 19, 'System Prompt Engineering', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-12-020', 'phase-12', 20, 'Eval-Driven AI Development', 16);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-001', 'phase-13', 1, 'IndexedDB', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-002', 'phase-13', 2, 'idb', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-003', 'phase-13', 3, 'Web Workers', 10);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-004', 'phase-13', 4, 'comlink', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-005', 'phase-13', 5, 'Broadcast Channel API', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-006', 'phase-13', 7, 'requestAnimationFrame', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-007', 'phase-13', 8, 'requestIdleCallback', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-008', 'phase-13', 6, 'View Transitions API', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-009', 'phase-13', 9, 'CSS Houdini', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-010', 'phase-13', 10, 'Yjs', 19);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-011', 'phase-13', 12, 'y-websocket', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-012', 'phase-13', 13, 'y-webrtc', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-013', 'phase-13', 14, 'y-indexeddb', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-014', 'phase-13', 11, 'Hocuspocus', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-015', 'phase-13', 16, 'ProseMirror', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-13-016', 'phase-13', 15, 'Tiptap', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-001', 'phase-14', 1, 'k6', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-002', 'phase-14', 2, 'k6 Cloud', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-003', 'phase-14', 3, 'Artillery', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-004', 'phase-14', 4, 'OWASP Top 10', 17);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-005', 'phase-14', 5, 'OWASP ZAP', 8);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-006', 'phase-14', 6, 'Nonce-Based CSP', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-007', 'phase-14', 7, 'JWT Algorithm Pinning', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-008', 'phase-14', 8, 'trufflehog', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-009', 'phase-14', 9, 'git-secrets', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-010', 'phase-14', 10, 'securityheaders.com', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-011', 'phase-14', 11, 'CSP Evaluator', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-012', 'phase-14', 12, 'Dependabot', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-013', 'phase-14', 13, 'npm audit', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-014', 'phase-14', 14, 'SOC 2 Basics', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-14-015', 'phase-14', 15, 'GDPR', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-001', 'phase-15', 1, 'Vite', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-002', 'phase-15', 2, 'tsup', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-003', 'phase-15', 3, '@next/bundle-analyzer', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-004', 'phase-15', 4, 'vite-bundle-visualizer', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-005', 'phase-15', 5, 'rollup-plugin-visualizer', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-006', 'phase-15', 6, 'lighthouse-ci', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-007', 'phase-15', 7, 'styled-components', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-008', 'phase-15', 8, 'Emotion', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-15-009', 'phase-15', 9, 'Linaria', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-001', 'phase-16', 1, 'AWS S3', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-002', 'phase-16', 2, 'Terraform', 31);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-003', 'phase-16', 3, 'Terraform Cloud', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-004', 'phase-16', 4, 'tfsec', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-005', 'phase-16', 5, 'Kubernetes', 46);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-006', 'phase-16', 6, 'kind (Kubernetes in Docker)', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-007', 'phase-16', 7, 'kubectl', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-008', 'phase-16', 8, 'Helm', 10);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-009', 'phase-16', 9, 'HPA (Horizontal Pod Autoscaler)', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-16-010', 'phase-16', 10, 'external-secrets', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-001', 'phase-17', 2, 'Cache-Aside Caching', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-002', 'phase-17', 3, 'Write-Through Caching', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-003', 'phase-17', 1, 'Optimistic Updates', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-004', 'phase-17', 5, 'Optimistic Locking', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-005', 'phase-17', 6, 'Pessimistic Locking', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-006', 'phase-17', 4, 'Idempotency', 7);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-007', 'phase-17', 7, 'Saga Pattern', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-008', 'phase-17', 8, 'Outbox Pattern', 10);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-009', 'phase-17', 9, 'Dead Letter Queue', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-010', 'phase-17', 10, 'Circuit Breaker', 8);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-011', 'phase-17', 11, 'Event-Driven Architecture', 13);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-012', 'phase-17', 12, 'CQRS (Command Query Responsibility Segregation)', NULL);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-013', 'phase-17', 13, 'Multi-Tenancy', 12);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-014', 'phase-17', 14, 'Blue-Green Deployments', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-17-015', 'phase-17', 15, 'Chaos Engineering', 9);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-001', 'phase-18', 1, 'Changesets', 5);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-002', 'phase-18', 2, 'ADRs (Architectural Decision Records)', 4);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-003', 'phase-18', 3, 'RFCs (Request for Comments)', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-004', 'phase-18', 4, 'DORA Metrics', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-005', 'phase-18', 5, 'Blameless Post-Mortems', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-006', 'phase-18', 6, 'Technical Debt Tracking', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-007', 'phase-18', 7, 'Estimation Tracking', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-008', 'phase-18', 8, 'Code Review Conventions', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-009', 'phase-18', 9, 'Ramp-Up Strategy', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-010', 'phase-18', 20, 'docs/adr/', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-011', 'phase-18', 10, 'ARCHITECTURE.md', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-012', 'phase-18', 11, 'DECISIONS.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-013', 'phase-18', 12, 'PERFORMANCE.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-014', 'phase-18', 13, 'SECURITY.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-015', 'phase-18', 14, 'MONITORING.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-016', 'phase-18', 15, 'OPERATIONS.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-017', 'phase-18', 19, 'incidents/', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-018', 'phase-18', 18, 'TECH_DEBT.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-019', 'phase-18', 16, 'PRODUCT_DECISIONS.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-18-020', 'phase-18', 17, 'READING_NOTES.md', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-001', 'phase-19', 1, 'JSONPlaceholder API', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-002', 'phase-19', 2, 'GitHub API', 6);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-003', 'phase-19', 3, 'Wellfound (formerly AngelList)', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-004', 'phase-19', 4, 'Instahyre', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-005', 'phase-19', 5, 'LinkedIn', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-006', 'phase-19', 6, 'Product Hunt', 2);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-007', 'phase-19', 7, 'Indie Hackers', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-008', 'phase-19', 8, 'SaaS India Slack', 1);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-009', 'phase-19', 9, 'dev.to', 3);
insert into public.topics (id, phase_id, order_index, title, estimated_hours) values ('topic-19-010', 'phase-19', 10, 'Hashnode', 1);

delete from public.exit_ladder;
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('A', 'phase-06', 'Junior Full-Stack', 'Junior Full-Stack', '₹6–10 LPA', 'Early-stage startups, dev agencies', 'Live URL, green CI badge, Docker deployment', 0);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('A2', 'phase-06b', 'Mobile-Capable Add-On', 'Mobile-Capable Add-On', '₹8–12 LPA', 'Roles valuing React Native experience', 'Working Expo app (offline-first field reporting)', 1);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('B', 'phase-07', 'Junior-to-Mid Full-Stack', 'Junior-to-Mid Full-Stack', '₹8–12 LPA', 'API-first companies (Postman, Hasura), fintech startups', 'Swagger UI link, OpenAPI spec, GraphQL knowledge', 2);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('★1', 'phase-08', 'Interview-Ready Junior-to-Mid', 'Interview-Ready Junior-to-Mid', '₹8–15 LPA', 'Series A/B startups, product companies', 'Portfolio + DSA readiness + system design basics', 3);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('C', 'phase-10', 'Mid Full-Stack (Production-Ready)', 'Mid Full-Stack (Production-Ready)', '₹12–18 LPA', 'Fintech, e-commerce, B2B SaaS', 'Razorpay integration, Sentry dashboard, Redis caching', 4);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('★2', 'phase-11', 'Mid-Level Full-Stack', 'Mid-Level Full-Stack', '₹15–25 LPA', 'High-traffic platforms, real-time heavy companies', 'WebSocket feature, search benchmarks, query optimization', 5);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('D', 'phase-12', 'AI-Capable Mid-Senior', 'AI-Capable Mid-Senior', '₹20–30 LPA', 'AI-native startups, LLM-powered products', 'RAG pipeline, multi-model routing, eval framework', 6);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('3', 'phase-17', 'Senior Full-Stack', 'Senior Full-Stack', '₹25–40 LPA', 'Late-stage unicorns, FAANG India, high-growth scale-ups', 'Kubernetes, Terraform, distributed systems patterns', 7);
insert into public.exit_ladder (exit_code, linked_phase, name, job_level, salary_range, target_companies, highlights, order_index) values ('E', 'phase-19', 'Complete Profile', 'Complete Profile', '₹35–50 LPA', 'Staff/Principal Engineer, Founding Engineer roles, global remote', 'Published npm package, ADRs, DORA metrics, 16 months of public learning', 8);

commit;